version: '3.8'

services:
  # PostgreSQL база данных
  db:
    image: postgres:15
    container_name: finance-db-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "18432:5432"
    networks:
      - finsecret_common_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis для кэша/сессий (опционально)
  redis:
    image: redis:7-alpine
    container_name: django_redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - finsecret_common_network
    command: redis-server --appendonly yes

  # Django приложение
  finsecret-django-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finsecret_django_app
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}|{{.ImageFullID}}|{{.FullID}}"
    restart: unless-stopped
    command: sh /app/scripts/start.sh
    volumes:
      - static_volume:/app/finance_planner/staticfiles
      - media_volume:/app/media
    ports:
      - "8800:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=finance-db-prod
      - USE_SQLITE=${USE_SQLITE:-False}
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - finsecret_common_network
      - db_internal_network


volumes:
  postgres_data:
  redis_data:
  static_volume:
    name: static_volume
  media_volume:
    name: media_volume

networks:
  finsecret_common_network:
    external: true
    name: finsecret_common_network
  db_internal_network:
    driver: bridge
