version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: django_app
    restart: unless-stopped
    command: sh /app/scripts/start_dev.sh
    volumes:
      - static_volume:/app/finance_planner/staticfiles
      - media_volume:/app/media
    ports:
      - "8800:8000"
    env_file:
      - .env.dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - django_network

  db:
    image: postgres:15
    container_name: finance_postgres
    restart: unless-stopped
    env_file:
      - .env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "18432:5432"
    networks:
      - django_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$$POSTGRES_USER\" -d \"$$POSTGRES_DB\"" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis для кэша/сессий (опционально)
  redis:
    image: redis:7-alpine
    container_name: django_redis
    restart: unless-stopped
    ports:
      - "16379:6379"
    volumes:
      - redis_data:/data
    networks:
      - django_network
    command: redis-server --appendonly yes

  # Nginx - ТОЧНО КАК НА ПРОДАКШЕНЕ
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    depends_on:
      - backend  # Изменили зависимость
    restart: unless-stopped
    ports:
      - "8090:80"  # Изменили на порт 8090 как на продакшене
      - "443:443"
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/static:ro
      - media_volume:/media:ro
    healthcheck:
      test: [ "CMD", "nginx", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - django_network

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  django_network:
    driver: bridge
